### ISSUE TITLE
`digistuff:advtouchscreen` dosn't accept formspec code

### ISSUE THREAD

**Issue by nixnoxus** [mt-mods/digistuff#27]
after update https://github.com/mt-mods/digistuff/commit/260f5b37069babf50e702edac77ffc964c5ee1ab
the `digistuff:advtouchscreen` still works, but it can no longer be reprogrammed with formspec.

Sample Code:
```lua
  digiline_send("ats",
       "size[8,4;]field[1,1;6,2;wish;Enter your wish A2;${wish}]"
    .."label[2,2;(no warranty)]"
    .."button_exit[2.25,3;3,1;submit;Send to santa claus]"
)
```

I'm not sure if this is a bug or intentional. But the compatibility with https://cheapiesystems.com/git/digistuff is lost :cry:

**Comment by SwissalpS** [comment]
thanks, that is a bug according to goals of re-write: https://github.com/mt-mods/digistuff/pull/25

**Comment by OgelGames** [comment]
Yes, that is intentional, `digistuff:advtouchscreen` no longer exists, `digistuff:touchscreen` replaces it.

`digistuff:advtouchscreen` was a "lazy" solution to the lack of functionality of `digistuff:touchscreen`: https://github.com/mt-mods/digistuff/commit/a38debb5924a7febcbe33617afbfda4722c0611e (albeit a much faster solution)

> thanks, that is a bug according to goals of re-write: #25

No, it was specifically mentioned that it was being aliased:

> - [x] Add alias for `digistuff:advtouchscreen`.

**Comment by SwissalpS** [comment]
oops, sorry.
