### ISSUE TITLE
Digilines pistons are able to push a LOT more nodes than they should

### ISSUE THREAD

**Issue by TheEt1234** [mt-mods/digistuff#55]
# Steps to reproduce:
- Have a digilines piston with the channel "p"
- have a long line of cobble (not too long though, or that may fail, but can be several tousands nodes long)
- Have a luacontroller with:
```lua
digiline_send("p",{
  action="extend",
  max = 0/0,
  allsticky=true,
  sound=""
})
```
- Observe the power

**Comment by S-S-X** [comment]
Can be fixed here for piston but digilines behavior very likely should be also changed on lua controller and pipeworks lua tube because of how nan is actually handled (or rather not handled or wrongfully assumed zero).
It could be good to actually make nan forbidden similar to functions or recursion, probably could also drop infinity if not already forbidden as it had some issues with serialization (might have been fixed or not but similar to nan has very little real use on digiline messages).

**Comment by TheEt1234** [comment]
> Can be fixed here for piston but digilines behavior very likely should be also changed on lua controller and pipeworks lua tube because of how nan is actually handled (or rather not handled or wrongfully assumed zero). It could be good to actually make nan forbidden similar to functions or recursion, probably could also drop infinity if not already forbidden as it had some issues with serialization (might have been fixed or not but similar to nan has very little real use on digiline messages).

should also be fixed here because that would probably require every single luacontroller fork to cooperate (or do some magic with digilines idk)

**Comment by TheEt1234** [comment]
> [minetest-mods/mesecons#667](https://github.com/minetest-mods/mesecons/pull/667) [mt-mods/pipeworks@8828183](https://github.com/mt-mods/pipeworks/commit/8828183befafdf1bf3a26e3b6303cc824da36b81) [mt-mods/mooncontroller@a72aa33](https://github.com/mt-mods/mooncontroller/commit/a72aa33c489d43d8992377a71c3358a491824467)

Oh cool

**Comment by OgelGames** [comment]
Fixed in the Luacontroller, Lua tube and Mooncontroller.
