### ISSUE TITLE
[Not a serious bug but still like bad] Autoclickers can burn any luacontroller connected to a touchscreen

### ISSUE THREAD

**Issue by TheEt1234** [mt-mods/digistuff#56]
# Steps to reproduce
1) have a touchscreen with the channel "ts"
2) have a luacontroller with the code
```lua
if event.type=="program" then
  digiline_send("ts",{command="clear"})
  digiline_send("ts",{command="add",element="button"})
end
```
3) enter the touchscreen and start spamming that button with an autoclicker 
## this can also be done with quit events i think, so you don't even need a button
# Current solutions:
- digicontrol mod [adds nodes that can limit the amount of messages on a wire]
- somehow making a weird setup that either clears the touchscreen or unplugs it using a digiline piston

**Comment by S-S-X** [comment]
Additionally, depending on max heat configuration, you don't really need any autoclicker just dozen fast clicks or with certain components you can also use mouse wheel.

Because max heat and overheating is not hard coded thing but tolerances can be very different based on server _(and people have built setups that do require a lot of messages for example in local singlepalyer worlds)_ it very likely is not that good idea to start adding configuration / protection for each digiline thing that accepts direct user input. Going that route would likely end up with multiple bad half baked implementations with varying compatibility which might actually be worse than current situation.

It would likely be better to add digiline message and digiline device restrictions either to some external rate limit / restriction mod (like mesecons_debug) or directly to digiline API.

Additionally unlimited input comes with many other generic issues and user input/message rate limiters very likely belong to engine and/or anticheat mods and/or server firewall that actually has ability to properly handle all cases like appropriate bursts while still providing protection against targeted attacks.

**Comment by TheEt1234** [comment]
maybe a way to solve this mess that is digilines (you need channel checking, type checking, nan checking, cooldowns, etc. on your digilines devices) could be to also make a library for doing that (maybe)

**Comment by OgelGames** [comment]
This is why digicontrol limiters exist.

**Comment by S-S-X** [comment]
Closing this for now as it does not seem to belong here, anyway feel free to reopen/comment if you think there's something that actually should be done in digistuff mod.
